### ISSUE TITLE
Argoverse v1 and / or v2

### ISSUE THREAD

**Issue by MTDzi** [NVlabs/trajdata#14]
I was looking for Argoverse dataset support in the README, but didn't find it.

Is it supported or planned in a future version?

**Comment by MTDzi** [comment]
@Leon0402 I figured I should ping someone, notifications don't always get through.

**Comment by Leon0402** [comment]
Hi, I saw your issue before as I enabled notifications for the whole repo (I assume @BorisIvanovic has them enabled automatically as the owner of this repo, but pinging him might help sometimes. But you be a little bit more patient than a day. I think he is a little bit busy right now with releasing a new paper).
I'm not owner or part of the team behind trajdata, I just contributed a few patches / issues, so I'm not the correct one to answer your question. I don't know if support is planned (It's not supported yet as far as I can tell). 
Having said that implementing it yourself is always an option. I wrote support for another dataset, which is only for my company though and therefore I didn't upstream it. If you're willing to put time and effort in this yourself, I can support you with some instructions regarding the trajdata side. I cannot (!) help you with Argoverse though. I never used it and I don't have time to invest it. 

How much effort this really is depends on argoverse. Basically you would need to convert agent data and map data in a specific format. This can be challanging or easy depending on the original format of argoverse and the provided apis. 
Argoverse seems like a more complex dataset (like nuScenes), but also offers an api. Some examples for the map can be found here: https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_map_tutorial.ipyn
So it should probably be not too hard depending on your knowledge of the dataset, python, trajectory prediction and general.

Let me know if you want to go down that road then I can give you some instructions on how to do it.

**Comment by MTDzi** [comment]
Hey @Leon0402 thanks for the swift reply!
OK, I understand the situation, thanks for a detailed intro!

Regarding Argoverse v1 -- I started working with it and its API a month ago and I feel sufficiently comfortable to be able to answer which map features required by `trajdata` are going to be difficult to produce, and which are going to be easy. I just need to familiarize myself with `trajdata`. 

But I wouldn't want to duplicate work that is (potentially) already been done. If @BorisIvanovic (or anyone) could give me a green light or any other indication that it might make sense for me to add this feature, I can start working on it.

**Comment by BorisIvanovic** [comment]
Hi @MTDzi ! Thanks for the question, and for your interest! I actually plan to release a pretty big update to trajdata soon (e.g., sometime next week, after the ICRA deadline :stuck_out_tongue: ). One of the updates will be the use of a canonical map format internally (so that different datasets don't have such a disparity when it comes to things like maps), as well as general speedups and other features.

If you're interested in contributing Argoverse back to trajdata, I'd be happy to review your pull request and green-light such a merge, but if I were you I would personally wait to start doing this until next week after I update trajdata. How does that sound? 

Also, I wasn't personally planning on supporting Argoverse, so it would be a definite positive if you were to do that!

**Comment by MTDzi** [comment]
Ah, awesome, thanks for the heads up!

Yes, I'd be very much interested in contributing the Argoverse dataloader (or loaders), and I agree that it makes more sense for me to wait if there's a large update incoming soon.

In the meantime, I'll familiarize myself with the nuScenes dataset and identify key differences with Argoverse.
In particular, I'll need to sort out if the overlap between these two datasets even justifies having a common format. You might already have some thoughts on this, but I don't want to take up much more of your time. I'll post any updates I might have here, in this issue.

Good luck with the ICRA submissions!

**Comment by BorisIvanovic** [comment]
The new update (v1.0.7) has been released!

**Comment by MTDzi** [comment]
Awesome!
And thanks for letting me know.
