### ISSUE TITLE
missing frames 

### ISSUE THREAD

**Issue by BestSonny** [NVlabs/trajdata#24]
Is the current repo supporting datasets with missing frames? If not, could you provide some hints on supporting it?

**Comment by BorisIvanovic** [comment]
Hi @BestSonny, 

Thank you for your interest and question! I don't believe there's anything inherently in trajdata that prevents missing frames from being stored, but to do so and keep all the other features you may want to populate missing timesteps with a known-missing value like `np.nan` or similar (in case you are missing frames from the middle of an agent's observed states).
