### ISSUE TITLE
DecodeError when parsing message in `waymo_dataset.py` and dependency-conflicts for trajdata

### ISSUE THREAD

**Issue by jxmmy7777** [NVlabs/trajdata#30]
Hello,

I encountered an issue when trying to run the `batch_example.py` script on Python `3.8.10`. The error seems to be related to parsing a protobuf message in the `waymo_dataset.py` file.

#### Steps to reproduce:

1. Setup the environment using the following command:
   ```bash
   pip install -e .[waymo]

The traceback is as follows:
```
Traceback (most recent call last):
  File "**/batch_example.py", line 55, in <module>
    main()
  File "**/batch_example.py", line 14, in main
    dataset = UnifiedDataset(
  File "**/dataset.py", line 304, in __init__
    env.cache_maps(
  File "**/waymo_dataset.py", line 373, in cache_maps
    self.cache_map(i, cache_path, map_cache_class, map_params)
  File "**/waymo_dataset.py", line 342, in cache_map
    scenario.ParseFromString(bytearray(data.numpy()))
google.protobuf.message.DecodeError: Error parsing message with type 'waymo.open_dataset.Scenario'
```

Also, I notice that if we do pip install -e .[nusc,lyft,waymo,interaction], there will be package versions conflict:

```
ERROR: Cannot install tensorflow==2.11.0, trajdata and trajdata[interaction,lyft,nusc,waymo]==1.3.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    trajdata[interaction,lyft,nusc,waymo] 1.3.3 depends on numpy>=1.19
    l5kit 1.5.0 depends on numpy~=1.19.0
    nuscenes-devkit 1.1.9 depends on numpy
    tensorflow 2.11.0 depends on numpy>=1.2
```

Would appreciate any insights or solutions regarding this. Thank you!

**Comment by meaten** [comment]
Someone, including me, would face the same error and spend several hours solving it.
Please download `waymo_open_dataset_motion_v_1_1_0/uncompressed/scenario`
, not `waymo_open_dataset_motion_v_1_1_0/uncompressed/tf_example`.
Please download `testing.tfrecord-00000-of-00150`, not `testing_tfexample.tfrecord-00000-of-00150`.
It's very confusing and easy to download the wrong files.
